packages:
  - api
  - web
  - packages/*

catalog:
  '@cool-midway/core': ^8.0.7
  '@cool-midway/rpc': ^8.0.1
  '@cool-midway/task': ^8.0.2
  '@midwayjs/bootstrap': ^3.20.3
  '@midwayjs/bundle-helper': ^1.3.0
  '@midwayjs/cache-manager': ^3.20.3
  '@midwayjs/core': ^3.20.3
  '@midwayjs/cron': ^3.20.3
  '@midwayjs/cross-domain': ^3.20.3
  '@midwayjs/info': ^3.20.3
  '@midwayjs/koa': ^3.20.3
  '@midwayjs/logger': ^3.4.2
  '@midwayjs/mock': ^3.20.3
  '@midwayjs/static-file': ^3.20.3
  '@midwayjs/typeorm': ^3.20.3
  '@midwayjs/upload': ^3.20.3
  '@midwayjs/validate': ^3.20.3
  '@types/jest': ^29.5.14
  '@yao-pkg/pkg': ^6.3.2
  adm-zip: ^0.5.16
  axios: ^1.13.2
  cron: ^4.1.3
  cross-env: ^7.0.3
  download: ^8.0.0
  jest: ^29.7.0
  jsonwebtoken: ^9.0.2
  lodash: ^4.17.21
  md5: ^2.3.0
  moment: ^2.30.1
  mwts: ^1.3.0
  mwtsc: ^1.15.1
  mysql2: ^3.14.0
  rimraf: ^6.0.1
  svg-captcha: ^1.4.0
  ts-jest: ^29.3.0
  tslib: ^2.8.1
  typeorm: npm:@cool-midway/typeorm@0.3.20
  uuid: ^11.1.0
  ws: ^8.18.1

catalogs:
  build:
    '@iconify-json/carbon': ^1.2.9
    '@vitejs/plugin-vue': ^5.2.4
    jsdom: ^26.1.0
    unocss: ^66.2.0
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.14.1
    '@types/node': ^22.15.31
    '@unocss/eslint-plugin': ^66.2.0
    '@vue-macros/volar': ^3.0.0-beta.14
    '@vue/test-utils': ^2.4.6
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.2.3
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/core': ^13.3.0
    vue: ^3.5.16
    vue-router: ^4.5.1
  conflicts_dev_22:
    '@types/node': '22'
  conflicts_dev_t5_8_2:
    typescript: ~5.8.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
